name: API Regression Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: |
          newman run collection.json \
            -e environment.json \
            --reporters cli,html,json \
            --reporter-html-export newman-report.html \
            --reporter-json-export newman-report.json

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-report
          path: newman-report.html
